### ISSUE TITLE
Feature request: Support for bundles placed at `Bundle` folder

### ISSUE THREAD

**Issue by igormukhingmailcom** [sonata-project/SonataEasyExtendsBundle#63] opened 2015-06-28 18:02 UTC
Hi.

That would be great if bundle will support also next directory structure: `Acme\Bundle\SomeBundle\AcmeSomeBundle`. Now only `Acme\SomeBundle\AcmeSomeBundle` supported (without `Bundle` in it).

That is output:

```
php app/console sonata:easy-extends:generate AcmeSomeBundle
Acme\Bundle\SomeBundle\AcmeSomeBundle : wrong folder structure
done!
```

**Comment by core23** [comment] 2016-08-27 17:37
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by johnpancoast** [comment] 2017-04-13 19:15
@core23 this is still an issue.

https://github.com/sonata-project/SonataEasyExtendsBundle/blob/2.x/Bundle/BundleMetadata.php#L204

It's making an assumption that all bundles will have this structure and many projects often have custom namespaces, deeper levels etc.

**Comment by jordisala1991** [comment] 2018-04-01 17:16
Related to #172 

Probably better to just improve this when thinking about flex.

Closing this one.

**Closed by jordisala1991** 2018-04-01 17:16 UTC
Labels: pending author
